"""initial revision user table

Revision ID: 81b19dd343fa
Revises: 
Create Date: 2020-03-10 21:59:09.345955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b19dd343fa'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urs_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.Unicode(), nullable=False),
    sa.Column('password', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urs_user_id'), 'urs_user', ['id'], unique=False)
    op.create_index(op.f('ix_urs_user_username'), 'urs_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urs_user_username'), table_name='urs_user')
    op.drop_index(op.f('ix_urs_user_id'), table_name='urs_user')
    op.drop_table('urs_user')
    # ### end Alembic commands ###
